/* Progress sync endpoint — a Cloudflare Worker storing one JSON document per
 * sync key, so a phone and a desktop can keep the same study progress without
 * exporting and importing a file by hand.
 *
 * It is deliberately almost nothing. All the difficult thinking about combining
 * two devices' progress lives in progress-backup.js and runs in the browser;
 * this end only has to store a blob, hand it back, and refuse a write that was
 * based on a version somebody else has already replaced.
 *
 * THE ONE PIECE OF REAL LOGIC IS THE VERSION CHECK
 *
 * Without it there is a silent lost update: phone reads v4, desktop reads v4,
 * phone writes v5, desktop writes its own v5 built from the stale read and the
 * phone's session is gone. So every write must say which version it is
 * replacing, and a write against a stale version is rejected with 409. The
 * client re-reads, merges again, and retries. Because the merge is idempotent
 * and order-independent, that retry always converges.
 *
 * AUTHENTICATION
 *
 * A single shared key, sent as a bearer token, generated by the first device
 * and carried to the second. There are no accounts. The key is never stored
 * here — the KV entry is named after its SHA-256, so a dump of this namespace
 * reveals no key that could be used to read anything.
 *
 * Anyone holding the key can read and write that progress. For study scores
 * with no personal data in them that is a reasonable trade for having no login,
 * but it is a real property of the design and not an oversight.
 *
 * DEPLOYING: see README.md in this folder.
 */

const MAX_BODY_BYTES = 2 * 1024 * 1024;   // a full progress document is ~150 KB
const MIN_KEY_LENGTH = 24;                // ~128 bits at the alphabet the client uses
const MAX_KEY_LENGTH = 128;

function cors(origin) {
  return {
    'Access-Control-Allow-Origin': origin || '*',
    'Access-Control-Allow-Methods': 'GET, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Authorization, Content-Type, If-Match',
    'Access-Control-Expose-Headers': 'ETag',
    'Access-Control-Max-Age': '86400',
    'Vary': 'Origin',
  };
}

function json(body, init, origin) {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Cache-Control': 'no-store',
      ...cors(origin),
      ...((init && init.headers) || {}),
    },
  });
}

/* The bearer token names the document. Hashing means the stored name cannot be
   turned back into a usable key. */
async function keyName(token) {
  const bytes = new TextEncoder().encode('aat-progress-v1:' + token);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return 'p:' + Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function bearer(request) {
  const h = request.headers.get('Authorization') || '';
  const m = /^Bearer\s+(.+)$/i.exec(h.trim());
  return m ? m[1].trim() : '';
}

export async function handleRequest(request, env) {
  const origin = request.headers.get('Origin') || '';
  const url = new URL(request.url);

  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: cors(origin) });
  }
  if (url.pathname !== '/state') {
    return json({ error: 'not_found' }, { status: 404 }, origin);
  }

  const token = bearer(request);
  if (token.length < MIN_KEY_LENGTH || token.length > MAX_KEY_LENGTH) {
    return json({ error: 'bad_key', message: 'Missing or malformed sync key.' }, { status: 401 }, origin);
  }
  const name = await keyName(token);

  if (request.method === 'GET') {
    const stored = await env.PROGRESS.get(name, { type: 'json' });
    if (!stored) return json({ error: 'empty', version: 0 }, { status: 404 }, origin);
    return json(stored, { status: 200, headers: { ETag: '"' + stored.version + '"' } }, origin);
  }

  if (request.method === 'PUT') {
    const raw = await request.text();
    if (raw.length > MAX_BODY_BYTES) {
      return json({ error: 'too_large' }, { status: 413 }, origin);
    }
    let doc;
    try { doc = JSON.parse(raw); }
    catch (e) { return json({ error: 'bad_json' }, { status: 400 }, origin); }
    if (!doc || typeof doc !== 'object' || !doc.keys || typeof doc.keys !== 'object') {
      return json({ error: 'bad_document' }, { status: 400 }, origin);
    }

    const current = await env.PROGRESS.get(name, { type: 'json' });
    const currentVersion = current ? current.version : 0;

    /* If-Match is required on every write. A client that does not send it is
       not participating in the version check, and letting it through would
       reintroduce exactly the lost update the check exists to prevent. */
    const ifMatch = (request.headers.get('If-Match') || '').replace(/"/g, '').trim();
    if (ifMatch === '') {
      return json({ error: 'missing_if_match' }, { status: 428 }, origin);
    }
    if (String(currentVersion) !== ifMatch) {
      return json(
        { error: 'conflict', version: currentVersion, message: 'Someone else wrote first — re-read and merge.' },
        { status: 409, headers: { ETag: '"' + currentVersion + '"' } },
        origin
      );
    }

    const next = {
      version: currentVersion + 1,
      updatedAt: new Date().toISOString(),
      keys: doc.keys,
    };
    await env.PROGRESS.put(name, JSON.stringify(next));
    return json(
      { version: next.version, updatedAt: next.updatedAt },
      { status: 200, headers: { ETag: '"' + next.version + '"' } },
      origin
    );
  }

  return json({ error: 'method_not_allowed' }, { status: 405 }, origin);
}

export default { fetch: handleRequest };
